export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "Auth/login",
    VALIDATE_PASSWORD_TOKEN: "Auth/validate-password-token",
    SEND_PASSWORD_LINK: "Auth/send-password-link",
  },
  CLUBS: {
    ALL: "Club/all",
    LIST: "Club",
    CLUB: "Club/",
    CLUB_DASHBOARD: "Club/dashboard/",
    CREATE: "Club/create",
    UPDATE: "Club/UpdateClub",
    DELETE: "Club/Status/",
    UPLOAD_CONTRACT: "Club/contracts/",
    ADD_CONTACT: "Club/contacts/",
    UPDATE_CONTACT: "Club/contacts/",
  },
  USERS: {
    ALL: "User/dashboard-statistics",
    USER: "User/",
    CREATE: "User/create",
    UPDATE: "User/update/",
    DELETE: "User/status/",
    CREATE_PASSWORD: "User/create-password",
  },
  FEDERATIONS: {
    LIST: "Federation/all",
    ALL: "Federation/federationlist",
    FEDERATION: "Federation/",
    CREATE: "Federation/create",
    UPDATE: "Federation/update/",
    DELETE: "Federation/",
    BY_COUNTRY: "Federation/by-country",
  },
  SUPPLIERS: {
    ALL: "Supplier/all",
    SUPPLIER: "Supplier/",
    CREATE: "Supplier/create",
    UPDATE: "Supplier/update/",
    DELETE: "Supplier/",
    BY_FEDERATION: "Supplier/by-federation",
  },
  AGE_CATEGORIES: {
    ALL: "Club/age-groups/",
    LIST: "AgeCategory/AgeCategories",
    AGE_CATEGORY: "AgeCategory/",
    CREATE: "AgeCategory/create",
    UPDATE: "AgeCategory/update/",
    DELETE: "AgeCategory/",
  },
  TEAMS: {
    LIST: "Teams",
    TEAM: "Teams/",
    CREATE: "Teams",
    UPDATE: "Teams",
    DELETE: "Teams/",
    BY_CLUB_AND_AGE_GROUP: "Teams/",
  },
  LEARNING_LINES: {
    LIST: "LearningLine",
    ALL: "LearningLine/all",
    LEARNING_LINE: "LearningLine/",
    CREATE: "LearningLine",
    UPDATE: "LearningLine/",
    DELETE: "LearningLine/",
    CONTENT_ALL: "LearningLine/content/all",
    WEEKS_MANAGE: "LearningLine/weeks/manage/",
    WEEK_BY_ID: "LearningLine/weeks/",
    WEEK_DUPLICATE: "LearningLine/weeks/duplicate/",
    DUPLICATE: "LearningLine/duplicate/",
    DASHBOARD: "LearningLine/dashboard/",
    EXPORT: "LearningLine/export/",
    UPDATE_WEEK_CONTENT: "LearningLine/weeks/content/",
  },
  LIBRARY: {
    LIST: "Library/content/all",
    CONTENT: "Library/content/",
    LIBRARY: "Library/library/",
    CREATE_UPDATE_COURSE: "Library/course/info/",
    CREATE_UPDATE_MODULE: "Library/course/module/",
    CREATE_UPDATE_LESSON: "Library/course/module/lesson/",
    CREATE: "Library/content",
    UPDATE: "Library/content/",
    DELETE: "Library/content/",
    CREATE_UPDATE_CONTENT_FILE: "Library/content/file/",
    MISC_DATA: "Library/content/all",
    SKILLS: "Library/skills",
  },
  DASHBOARD: {
    RECENT_FEEDBACKS: "/Dashboard/recent-feedbacks",
  },
  Localization: "Users/localization",
};
